### ISSUE TITLE
今日头条互娱研发上海HR Sunny的问候

### ISSUE THREAD

**Issue by flysunnyDW** [bajdcc/clib2d#1]
您好，我是今日头条互娱研发上海HR Sunny，有幸看到您的OpenGL项目分享，希望有机会和您认识，冒昧提个issues，不知道是否方便加个微信沟通，我的微信是fengzhigu-s，期待您的回复。

**Comment by wgtdkp** [comment]
@flysunnyDW 现在的HR都这么专业了吗？哈哈哈

**Comment by bajdcc** [comment]
😂
